[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "light"
primaryColor = "#00b4ff"
backgroundColor = "#f6f9fc"
secondaryBackgroundColor = "#e8f2fa"
textColor = "#1e2732"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false